# Generated by Django 4.1.7 on 2023-03-21 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tthapp', '0002_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='comments',
            new_name='comment',
        ),
    ]
