# Generated by Django 4.1.7 on 2023-04-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tthapp', '0010_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expdate',
            field=models.DateField(max_length=255),
        ),
    ]
